### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by gousasin** [bndw/wifi-card#104]
Hi there :)

I did a German translation for the app. Feel free to implement it.

English <=> German

WiFi Login <=> WLAN Zugangsdaten:

Network name <=> Netzwerkname:

WiFi Network name <=> WLAN Netzwerkname

Password <=> Passwort:

Hide password field before printing <=> Passwortfeld vor dem Drucken ausblenden

Encryption: <=> Verschlüsselung:

None <=> Keine

Point your phone's camera at the QR Code to connect automatically <=> Richten Sie die Kamera Ihres Telefons auf den QR-Code um automatisch eine Verbindung herzustellen.

**Comment by gousasin** [comment]
Did not see that PR. All right, I'll close this issue. Thanks!

**Comment by Andanan** [comment]
I just added some of these changes along with some other improvements as suggestions to #98
