### ISSUE TITLE
Unable ro run in Docker

### ISSUE THREAD

**Issue by nxion** [bndw/wifi-card#11]
Hello,

I am having a difficult time understanding from the README how to run this from Docker. I'm relatively new to Docker and this seemed like a fun project to explore with.

Based on the read me I should be able to run 
```
make run
```

And It would run but I'm sure that there is more to it than that.

**Comment by bndw** [comment]
👋 Hi @nxion,

[Make](https://en.wikipedia.org/wiki/Make_(software)) is just a convenient way to run the more complex docker command--
```
docker run --rm -p 8080:80 bndw/wifi-card:latest
```

Run that and open http://localhost:8080. Feel free to reply here if you get stuck.

**Comment by nxion** [comment]
Thanks for replying. I feel kinda stupid now for asking :|. The above worked perfectly. Thank you for such an awesome project.
