### ISSUE TITLE
Docs: Language contribution guide

### ISSUE THREAD

**Issue by bndw** [bndw/wifi-card#117]
It would be helpful to document the process of contributing a translation. Off the top of my head, the steps are roughly:
1. Add a translation to `./src/i18n.js`
2. Add the language option to `./src/app.js`. Use the format e.g. `French (Français)`
3. Run `make fmt.write` to format your changes with Prettier

**Comment by YoussefMahmod** [comment]
Hi @A-Tokyo  I think you should consider **RTL Format**.

**Comment by A-Tokyo** [comment]
Thanks for the awesome work!

There's another step regarding languages that require `RTL` direction (step 3):

1. Add a translation to ./src/i18n.js
1. Add the language option to ./src/app.js. Use the format e.g. French (Français)
1. If the languages added require RTL direction, add the language keys to `RTL_LANGUAGES` constant in `./src/app.js`.
1. Run make fmt.write to format your changes with Prettier

**Comment by Andanan** [comment]
How about:

5. Add your name to the translation-table in `README.md`

**Comment by Teraskull** [comment]
What about adding a separate language ini or json file instead of putting everything in App.js? Easier to contribute to.

**Comment by Baoyuantop** [comment]
With more and more languages, it’s time for us to consider separating different languages.

**Comment by A-Tokyo** [comment]
This PR https://github.com/bndw/wifi-card/pull/128 automates the 3rd step (running prettier), so we don't need it anymore.

**Comment by A-Tokyo** [comment]
We can now remove the prettier step 🚀 It was automated in this PR https://github.com/bndw/wifi-card/pull/128
