### ISSUE TITLE
Hidden SSID toggle?

### ISSUE THREAD

**Issue by baryoncascade** [bndw/wifi-card#12]
Is there a way to toggle on 'hidden' for the SSID type?

**Comment by bndw** [comment]
Hi @baryoncascade,

There is no support for toggling 'hidden' SSID types in this tool, but it looks like the [protocol supports it](https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11).

**Comment by baryoncascade** [comment]
Thanks for the reply. I found another similar project that does allow for indicating the referenced SSID is hidden, and that QR code worked as expected. Your tool is more directly useful for printing, though!
