### ISSUE TITLE
Support TypeScript for the application

### ISSUE THREAD

**Issue by Baoyuantop** [bndw/wifi-card#135]
Do we have any plan to support TypeScript for the entire application?

As we all know, this makes the entire project easier to maintain, especially the current project code is increasing.

**Comment by olekstomek** [comment]
With this change, it would be nice to rewrite/convert the current code to TypeScript. Or will we have a mix of TypeScript and JavaScript?

**Comment by Baoyuantop** [comment]
Complete rewrite step by step

**Comment by bndw** [comment]
There are no plans to rewrite this in TypeScript at this time. Perhaps once things slow down again and the codebase matures a bit more, we can revisit.
