### ISSUE TITLE
New user may see wrong language !

### ISSUE THREAD

**Issue by PushpenderSaini0** [bndw/wifi-card#152]
The `i18next-browser-languagedetector` plugin detects my browser language as `en-US`
but that's not present in selector so it shows me the first option `Arabic` but the language is set to `en`
This can confuse a new user !

To reproduce this bug i clean my browser storage and all cache
so that i am like a new user on the site.

# Preview

![ps](https://user-images.githubusercontent.com/54404738/127688894-3665516f-067e-4020-b02a-3d59fe147f2f.gif)

**Comment by bndw** [comment]
Whoops, this was probably a regression from https://github.com/bndw/wifi-card/pull/149. I'll get a patch in.
