### ISSUE TITLE
Back-port changes across translations

### ISSUE THREAD

**Issue by bndw** [bndw/wifi-card#171]
Add/Update the following translation keys
```
'wifi.password.hide': 'Hide password',
'wifi.name.hiddenSSID': 'Hidden SSID,
'wifi.alert.password.length.5':
    'Password must be at least 5 characters, or change the encryption to "None"',
'wifi.alert.password.length.8':
    'Password must be at least 8 characters, or change the encryption to "None"',
```
If the below language authors would kindly translate the above 4 keys, either as a comment or pull request 
to this branch, it would be greatly appreciated ❤️

- [x] Chinese, https://github.com/bndw/wifi-card/pull/190
- [x] Spanish, https://github.com/bndw/wifi-card/pull/193
- [x] Portuguese, https://github.com/bndw/wifi-card/pull/211
- [x] Portuguese (Brazil), https://github.com/bndw/wifi-card/pull/211
- [x] Japanese, https://github.com/bndw/wifi-card/pull/197
- [x] Russian, https://github.com/bndw/wifi-card/pull/190
- [x] Ukrainian, https://github.com/bndw/wifi-card/pull/190
- [x] Dutch, https://github.com/bndw/wifi-card/pull/206
- [x] French, https://github.com/bndw/wifi-card/pull/192 
- [x] Hindi, https://github.com/bndw/wifi-card/pull/211
- [x] Catalan,  https://github.com/bndw/wifi-card/pull/191
- [x] German, https://github.com/bndw/wifi-card/pull/213
- [x] Indonesia, https://github.com/bndw/wifi-card/pull/206
- [x] Polish, https://github.com/bndw/wifi-card/pull/195
- [x] Arabic, https://github.com/bndw/wifi-card/pull/200
- [x] Occitan, https://github.com/bndw/wifi-card/pull/191
- [x] Italian, https://github.com/bndw/wifi-card/pull/220
- [x] Korean, https://github.com/bndw/wifi-card/pull/194
- [x] Norwegian, https://github.com/bndw/wifi-card/pull/205
- [x] Hungarian, https://github.com/bndw/wifi-card/pull/193
- [x] Serbian, https://github.com/bndw/wifi-card/pull/206
- [x] Turkish
- [x] Urdu

**Comment by olekstomek** [comment]
To translate:
`'wifi.name.hiddenSSID': 'Hidden SSID',`
It's using in this PR: https://github.com/bndw/wifi-card/pull/101

**Comment by Teraskull** [comment]
Translations for both #101 and #166.

`Ukrainian`:
```js
'wifi.name.hiddenSSID': 'Прихований SSID',
'wifi.password.hide': 'Приховати поле пароля',
'wifi.alert.password.length.5': 'Пароль повинен складатися не менше ніж з 5 символів, в іншому випадку змініть шифрування на "Немає"',
'wifi.alert.password.length.8': 'Пароль повинен складатися не менше ніж з 8 символів, в іншому випадку змініть шифрування на "Немає"'
```

`Russian`:
```js
'wifi.name.hiddenSSID': 'Скрытый SSID',
'wifi.password.hide': 'Скрыть поле пароля',
'wifi.alert.password.length.5': 'Пароль должен состоять не менее чем из 5 символов, в противном случае измените шифрование на "Нет"',
'wifi.alert.password.length.8': 'Пароль должен состоять не менее чем из 8 символов, в противном случае измените шифрование на "Нет"'
```

**Comment by Baoyuantop** [comment]
`Chinese `

```
'wifi.password.hide': '隐藏密码',
'wifi.alert.password.length.5': '密码必须至少为 5 个字符，或将加密更改为“无”',
'wifi.alert.password.length.8': '密码必须至少为 5 个字符，或将加密更改为“无”'
```

**Comment by bndw** [comment]
Thanks @Baoyuantop! -- could you also help with this one?
```
'wifi.name.hiddenSSID': 'Hidden SSID,
```

**Comment by oscfdezdz** [comment]
`Spanish`

```
'wifi.password.hide': 'Ocultar contraseña',
'wifi.name.hiddenSSID': 'SSID oculta',
'wifi.alert.password.length.5':
    'La contraseña debe tener al menos 5 caracteres, o cambiar el cifrado a "Ninguno"',
'wifi.alert.password.length.8':
    'La contraseña debe tener al menos 8 caracteres, o cambiar el cifrado a "Ninguno"',
```

**Comment by munkacsimark** [comment]
`Hungarian`

```
'wifi.password.hide': 'Jelszó elrejtése',
'wifi.name.hiddenSSID': 'Rejtett SSID,
'wifi.alert.password.length.5':
    'A jelszó minimum 5 karakter legyen, vagy állítsd a titkosítást "Nincs"-re',
'wifi.alert.password.length.8':
    'A jelszó minimum 8 karakter legyen, vagy állítsd a titkosítást "Nincs"-re',
```

**Comment by nyancodeid** [comment]
`Indonesia`

```
'wifi.password.hide': 'Sembunyikan kata sandi',
'wifi.name.hiddenSSID': 'Sembunyikan SSID',
'wifi.alert.password.length.5':
    'Kata sandi minimal harus 5 karakter, atau ubah enkripsi menjadi "Tidak ada"',
'wifi.alert.password.length.8':
    'Kata sandi minimal harus 8 karakter, atau ubah enkripsi menjadi "Tidak ada"',
```

**Comment by DEmanderbag** [comment]
In case a pull request is needed I will be able to do that later today.

`Serbian Latin update`

'wifi.password.hide': 'Sakri šifru',
'wifi.name.hiddenSSID': 'Sakriven SSID ',
'wifi.alert.password.length.5':
    'Šifra mora imati minimum 5 karaktera ili promeni enkripciju na "Nema"',
'wifi.alert.password.length.8':
    'Šifra mora imati minimum 8 karaktera ili promeni enkripciju na "Nema"',

`Serbian Cyrillic update`

'wifi.password.hide': 'Сакри шифру ',
'wifi.name.hiddenSSID': 'Сакривен SSID ',
'wifi.alert.password.length.5':
    'Шифра мора имати минимум 5 карактера или промени енкрипцију на "Нема"',
'wifi.alert.password.length.8':
    'Шифра мора имати минимум 8 карактера или промени енкрипцију на "Нема"',

**Comment by wouterbrink** [comment]
`Dutch`

    'wifi.password.hide': 'Verberg wachtwoord',
    'wifi.name.hiddenSSID': 'Verberg SSID,
    'wifi.alert.password.length.5':
        'Wachtwoord moet ten minste 5 tekens bevatten, of verander de encryptie naar "Geen"',
    'wifi.alert.password.length.8':
        Wachtwoord moet ten minste 8 tekens bevatten, of verander de encryptie naar "Geen"',

**Comment by bndw** [comment]
@pedrorenan would you mind helping with the translation update for Portuguese?
@ismaelpereira would you mind helping with the translation update for Portuguese Brazil?
@rizaergun would you mind helping with the translation update for Turkish?
@PushpenderSaini0 would you mind helping with the translation update for Hindi?
@devofthings would you mind helping with the translation update for German?
@pasmimmo would you mind helping with the translation update for Italian?
@mHassan11 would you mind helping with the translation update for Urdu?

If you could simply add a comment here, translating the following:
```
'wifi.password.hide': 'Hide password',
'wifi.name.hiddenSSID': 'Hidden SSID,
'wifi.alert.password.length.5':
    'Password must be at least 5 characters, or change the encryption to "None"',
'wifi.alert.password.length.8':
    'Password must be at least 8 characters, or change the encryption to "None"',
```

**Comment by PushpenderSaini0** [comment]
`HINDI`
```
'wifi.password.hide': 'पासवर्ड छुपाएं',
'wifi.name.hiddenSSID': 'छिपा हुआ SSID,
'wifi.alert.password.length.5':
    'पासवर्ड कम से कम 5 अक्षरों का होना चाहिए, या एन्क्रिप्शन को "कोई नहीं" में बदलें',
'wifi.alert.password.length.8':
    'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए, या एन्क्रिप्शन को "कोई नहीं" में बदलें',
```

**Comment by pedrorenan** [comment]
Portuguese

```
'wifi.password.hide': 'Esconder o campo de senha antes da impressão,
'wifi.name.hiddenSSID': 'Esconder nome da rede antes da impressão,
'wifi.alert.password.length.5':
    'A senha precisa ter no mínimo 5 dígitos, ou alterar a criptografia para "Nenhum"',
'wifi.alert.password.length.8':
    'A senha precisa ter no mínimo 8 dígitos, ou alterar a criptografia para "Nenhum"',
```

**Comment by ismaelpereira** [comment]
Brazilian Portuguese

`'wifi.password.hide': 'Esconder Senha',
'wifi.name.hiddenSSID': 'Esconder SSID,
'wifi.alert.password.length.5':
    'Sua senha deve ter pelo menos 5 caracteres, ou  altere a criptografia para "Nenhum"',
'wifi.alert.password.length.8':
    'Sua senha deve ter pelo menos 8 caracteres, ou  altere a criptografia para "Nenhum"',
`

**Comment by LionelKarlen** [comment]
German

```
'wifi.password.hide': 'Passwort verstecken',
'wifi.name.hiddenSSID': 'Versteckte SSID,
'wifi.alert.password.length.5':
    'Das Passwort muss mindestends 5 Zeichen lang sein, oder stelle die Verschlüsselung auf "Keine"',
'wifi.alert.password.length.8':
    'Das Passwort muss mindestends 8 Zeichen lang sein, oder stelle die Verschlüsselung auf "Keine"',
'wifi.password.encryption.none': 'Keine',
```
