### ISSUE TITLE
TypeError: Cannot read property 'rtl' of undefined

### ISSUE THREAD

**Issue by dv336699** [bndw/wifi-card#173]
Looks like one of these PRs broke the website?

https://github.com/bndw/wifi-card/pulls?q=rtl

Using Brave Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (x86_64)

![image](https://user-images.githubusercontent.com/930792/128558291-0d3a747d-5404-4e20-ad8e-49e4a8d7787a.png)

**Comment by bndw** [comment]
Dupe of https://github.com/bndw/wifi-card/issues/172

**Comment by bndw** [comment]
@dv336699 This has been fixed. If you're still having a problem, feel free to reopen.
