### ISSUE TITLE
White page on mobile view in mobile Chrome

### ISSUE THREAD

**Issue by olekstomek** [bndw/wifi-card#179]
If ❌ it means that I see white page. 

|  	|  Not incognito	| Incognito 	|  
|:---:	|:---:	|:---:	|
|  	https://wificard.io/| ❌| ❌| 
|  	https://dev.wificard.io/|🆗|❌| 

I have no logs because it is a mobile version of the browser, so I can't see it. I checked in the browser on the PC, I selected the option that I use smartphone, but in this case the problem does not occur.
When testing in mobile Chrome and selecting the desktop view option, the page loads correctly. So the problem is with loading the mobile version.

Web browser: Chrome 92.0.4515.131
Android 10

![1628372454599](https://user-images.githubusercontent.com/26818304/128614656-9b9fbe99-7ada-4484-af23-142e2fd0f2f4.jpg)

Not incognito, on left wificard.io, on right **dev**.wificard.io:
![1628372454594](https://user-images.githubusercontent.com/26818304/128614648-c06271aa-14b9-4b09-aa08-6da9ae4dd886.jpg)

**Comment by bndw** [comment]
Both https://wificard.io and https://dev.wificard.io are running the same version, https://github.com/bndw/wifi-card/commit/df6d62c397992aef26c3abb26ad667bcbc7184ad, so it's strange you would see different behavior. Perhaps you have previously visited wificard.io but not dev.wificard.io? 

This could be caching, where the index.html page is being cached somewhere (cloud, device) with the old fingerprinted assets which are no longer available.

**Comment by olekstomek** [comment]
I checked on another device and it's fine. My mistake. The problem is my device.
