### ISSUE TITLE
Incorrect language in the language drop-down list if a language other than English

### ISSUE THREAD

**Issue by olekstomek** [bndw/wifi-card#180]
The website detects the Polish language and presents the version of the website in this language. However, in the drop-down list, the currently indicated language is English instead of Polish in this case.

Web browser: Chrome 92.0.4515.131
Android 10
dev.wificard.io (because I [can't open on mobile Chrome wificard.io](https://github.com/bndw/wifi-card/issues/179)):
![1628372454589](https://user-images.githubusercontent.com/26818304/128614671-02cc9f9a-7460-42a3-bfde-fb62226c40d6.jpg)

Web browser: built into Android 10 MIUI Global 12.0.4, browser V12.11.4-gn 
Android 10
wificard.io (because I can open here wificard.io)
![1628372454604](https://user-images.githubusercontent.com/26818304/128614670-3bb5080b-3655-4b52-ba36-f5f6f1fcbddc.jpg)

**Comment by bndw** [comment]
This is possibly related to this addition: https://github.com/bndw/wifi-card/blame/master/src/components/Settings.js#L31

**Comment by bndw** [comment]
@olekstomek I've deployed a potential fix to https://dev.wificard.io. Would you mind confirming if that resolves the issue?

**Comment by olekstomek** [comment]
@bndw confirmed, it works perfect.
