### ISSUE TITLE
Block Iran IP?!

### ISSUE THREAD

**Issue by sina-yeganeh** [bndw/wifi-card#185]

**Comment by bndw** [comment]
Are you asking if https://wificard.io is explicitly blocking Iranian IP addresses? No, I'm not blocking Iran or any geographical regions from accessing the website.

However, the site is running on AWS and it [looks like Amazon has a history with Iran](https://html.duckduckgo.com/html?q=amazon%20aws%20blocking%20iran). Sorry for any inconvenience. The README has instructions for running the website locally.
