### ISSUE TITLE
Auto Identify wifi

### ISSUE THREAD

**Issue by rpradosilva** [bndw/wifi-card#216]
Hi everyone,

The app is really cool!!!

I suggest improving the experience by automating wi-fi identification via browser permissions, but manual configuration is still an alternative.

Example: [https://www.speedtest.net/]( https://www.speedtest.net/)

What do you think?

**Comment by olekstomek** [comment]
Is it possible? The informations on speedtest.net are non-local network information.

**Comment by rpradosilva** [comment]
I researching npm libs, this is an initial idea:

Lib: `npm install wifiscanner` 

Wi-fi list with some data:

```js
const wifiscanner = require("wifiscanner");

//Returns appropriate instance of a wifi scanner
const scanner = wifiscanner();

scanner.scan((error, networks) => {
  if (error) {
    console.error(error);
  } else {
    console.table(networks);
  }
});
```

What do you think?

**Comment by Baoyuantop** [comment]
What is the effect of this?

**Comment by olekstomek** [comment]
It's a convenient solution. The user can click the button to automatically complete the data about the network to which he is currently connected. This saves time and the possibility of mistakes. A very good idea for me.

**Comment by bndw** [comment]
This is a cool idea, but I don't think it's a good fit for this project. I want to keep the experience simple and expected. If a website like wificard.io automatically displayed my home wifi network details, I'd be caught off guard. 

Again, I think this is a really cool idea but not a good fit for this project.
