### ISSUE TITLE
Adding project info to pages aggregating open source and issues projects

### ISSUE THREAD

**Issue by olekstomek** [bndw/wifi-card#218]
For greater interest in contributing to the project, you can add the project to pages that gather information about open source projects and gather information about issues, e.g.:

- [codetriage.com](https://github.com/codetriage/codetriage)
- [up-for-grabs.net/](https://github.com/up-for-grabs/up-for-grabs.net)
- [goodfirstissues.com](https://github.com/darensin01/goodfirstissues)
- [goodfirstissue.dev/](https://goodfirstissue.dev/)
- others...

Maybe good point is add project to [Hacktoberfest](https://hacktoberfest.digitalocean.com/)?

**Comment by bndw** [comment]
To be honest, I'm not sure there is much contribution needed aside from the Safari-only bugfix (very minor) and backporting 3 language translations (nice to have). From a feature standpoint I'm happy with the current functionality.
