### ISSUE TITLE
TLS encryption

### ISSUE THREAD

**Issue by str8edgedave** [bndw/wifi-card#262]
I'm using wifi-card as a container with Podman. Is it possible to use SSL Certificates with wifi-card?

I'm using nginx as a reverse proxy with a certificate from Let's Encrypt. I'd like to be able to volume mount my SSL certificate and key to ensure end-to-end encryption.

**Comment by bndw** [comment]
If you want TLS between your nginx reverse proxy and the wifi-card container then you'd need to configure the nginx [base image](https://github.com/bndw/wifi-card/blob/master/Dockerfile#L11). You'd probably need to volume mount a custom nginx.config and key material. See the [nginx dockerhub](https://hub.docker.com/_/nginx/) page for some more info. Good luck!

**Comment by str8edgedave** [comment]
All good. Thanks for responding. Happy holidays!
