### ISSUE TITLE
iPhone "no usable data found" when open network

### ISSUE THREAD

**Issue by Thoroslives** [bndw/wifi-card#265]
Have QR set to open security

Works using multiple Android devices
Will not work with Apple devices just states "no usable data found" when trying to scan

To recreate, Set to open security. It seems all other settings don't affect it.

**Comment by bndw** [comment]
@Thoroslives Thanks for the report, this has been resolved.

**Comment by Thoroslives** [comment]
No worries, is this now reflected in the webpage output?

**Comment by bndw** [comment]
Yes, https://wificard.io has been updated
