### ISSUE TITLE
Feature Request > Suggestions for Space Usage/Efficiency on the Resulting Papers. 

### ISSUE THREAD

**Issue by SecularSteve** [bndw/wifi-card#269]
First of all, a "Cover The Whole Page" Button.

[test-card.pdf](https://github.com/bndw/wifi-card/files/11435620/test-card.pdf)

Seems like a waste of space, even on Landscape.

I can at the very least understand the Width on Portrait, but the waste of space is still very evident.

This could come in useful for those people who are both running a business, and need something to put on their walls for fast customer convenience.

But that's just my suggestion. Maybe an "Add Background" button instead, or a "Change Theme" option, just to get rid of the monotony. It's open source after all.

It could also include the option to add another QR Card beneath the above one on the paper/page in case the owner is running a separate 5G connection on the same network (with possibly a different password).

But again, those are all my suggestions.

**Comment by bndw** [comment]
There have been a handful of ideas for enhancing the print outs over the years (see: #63 #31 #30) but ultimately it would require a lot of design + coding work to make it handle all of the edge cases. 

I'd be willing to review a proposal and/or implementation, but I'm afraid it's not something I'm personally interested in pursuing.
