### ISSUE TITLE
Nginx Config 

### ISSUE THREAD

**Issue by wxyShine** [bndw/wifi-card#277]
```nginx
location   ^~  /wifi-card/ {
    proxy_pass http://172.17.0.1:8096/;
    proxy_redirect  off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
```

This configures the home page to come out, static resources appear 404

**Comment by bndw** [comment]
Are you having this problem when running the Docker image?

**Comment by wxyShine** [comment]
> Are you having this problem when running the Docker image?

yes  docker

**Comment by bndw** [comment]
The [bndw/wifi-card](https://hub.docker.com/r/bndw/wifi-card) Docker image uses the [nginx](https://hub.docker.com/_/nginx) base image. You should be able to provide your own nginx config file when you run the image, e.g.

```
docker run -v /host/path/nginx.conf:/etc/nginx/nginx.conf bndw/wifi-card
```

**Comment by bndw** [comment]
@wxyShine I'm going to close this issue as I believe passing in your own nginx config to the docker container is the best solution.
