### ISSUE TITLE
The minimum length of the WiFi password to prevent confusion

### ISSUE THREAD

**Issue by olekstomek** [bndw/wifi-card#29]
WPA-PSK minimum WPA length is 8 characters. For a 40 bit WEP  (rrobably very rare case) network the password is 5 characters. 
To prevent someone forgot to enter the minimum number of characters by mistake, it may be worth adding a warning.

**Comment by bndw** [comment]
Hi @olekstomek, 

Great idea, minimum length validation on the password input would be nice! WEP is not a concern as this project is [hard coded](https://github.com/bndw/wifi-card/blob/master/src/components/Card.js#L30) to for WPA.

**Comment by olekstomek** [comment]
Thanks
