### ISSUE TITLE
Generating PDF vertcally

### ISSUE THREAD

**Issue by olekstomek** [bndw/wifi-card#30]
Generating PDF vertically is useful. Currently, there is an option to only generate PDF horizontally.

**Comment by bndw** [comment]
Hi @olekstomek,

Cool idea. I'd be happy to review a pull request if you'd like to contribute the ability to change the print orientation.

**Comment by bndw** [comment]
Hi @olekstomek,

Both Firefox and Chrome support changing print orentation in the print dialog:
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/4248167/124403347-b8740000-dcea-11eb-8b23-4232367b7bec.png">

**Comment by olekstomek** [comment]
Hi @bndw, that's not what i meant and i wrote my thought inaccurately. Let's say I have a vertical frame and I would like to insert a printed document. I marked it in green in the attachment how I would like to cut it.
![generated_pdf_wifi](https://user-images.githubusercontent.com/26818304/124492470-cb530700-ddb4-11eb-96dc-5a5c6b3623b1.JPG)
I know that the qr code can be scanned without a problem, but reading the letters for a human is difficult if I put the document in its current form vertically, eg.:
![generated_pdf_wifi-vertically](https://user-images.githubusercontent.com/26818304/124492923-57fdc500-ddb5-11eb-8348-1e6f1207de23.JPG)
In this case, network name and password are probably best at the bottom of qr code.

**Comment by bndw** [comment]
@olekstomek thanks for the clarification, I think a landscape/portrait orientation toggle could be a nice enhancement. I'd be happy to review a pull request if it's something you'd like to contribute.
