### ISSUE TITLE
Hide the password on the generated document

### ISSUE THREAD

**Issue by olekstomek** [bndw/wifi-card#32]
The ability to hide a password written with text on the generated document.

**Comment by bndw** [comment]
Hi @olekstomek,

Cool idea. I'd be happy to review a pull request if you'd like to contribute the ability to hide the password text. I think you could do it natively in CSS with the `#password` input selector.

**Comment by olekstomek** [comment]
I will only mention that currently natively `#password` cannot be used for textarea (https://github.com/bndw/wifi-card/pull/34)
It's possible to hide the label with password and textarea by CSS, e.g.:
`.hidden {
  opacity: 0;
}`
But I don't think it will be good. Better to write CSS for the textarea which will behave the same as the native `#password` for input.

**Comment by bndw** [comment]
An alternative approach, shown in https://github.com/bndw/wifi-card/pull/41/files, would be to obfuscate the plaintext password with `text-security: disc` instead of hiding the element.

**Comment by bndw** [comment]
Unfortunately, it appears [webkit text-security](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security) does not work in Firefox (`-moz-text-security` is not recognized) so this won't be a viable option.

Looks like the best (only) solution is to hide the password textarea from the printout.

**Comment by bndw** [comment]
Fixed in #42
