### ISSUE TITLE
Feature request: Option to select encryption mode

### ISSUE THREAD

**Issue by gokaygurcan** [bndw/wifi-card#39]
Hi,

There're some cases people create public networks and manage them with another way/device (like hotspots in hotels). Keeping password field mandatory basically prevents creating passwordless network cards. 

It'd be nicer if there's an option to choose encryption, so based on selection password can be optional/ignored etc.

Here's the line that creates the qr value: https://github.com/bndw/wifi-card/blob/master/src/components/Card.js#L45
And here's more info about possible encryption values: https://en.wikipedia.org/wiki/QR_code#Joining_a_Wi%E2%80%91Fi_network

```bash
          ┌────────────────────────────────────────────────── ssid
          │           ┌────────────────────────────────────── encryption mode
          │           │                ┌───────────────────── password
          │           │                │               ┌───── hidden/visible flag
          │           │                │               │
WIFI:S:<SSID>;T:<WEP|WPA|blank>;P:<PASSWORD>;H:<true|false|blank>;
```

**Comment by bndw** [comment]
Hi @gokaygurcan,

I understand you'd like the option to select encryption type, where selecting "none" would disable the password input and in turn support public networks-- is this correct? For the SSID `myNetwork` with no password, you'd expect `WIFI:S:myNetwork;T:;P:;H:;` ?

**Comment by gokaygurcan** [comment]
Yup, totally got it right. Sorry if it wasn't clear in the first place :)

**Comment by olekstomek** [comment]
Hidden SSID wifi network can not be connected: https://github.com/bndw/wifi-card/issues/96
