### ISSUE TITLE
Please use a seriffed font for password field

### ISSUE THREAD

**Issue by welby12** [bndw/wifi-card#4]
My wifi password has a capital "i" in it. Would be great if a seriffed font was used to display the password, since it is virtually indistinguishable from a lowercase "L" with a sans-serif font. 

I understand the goal of this project is to NOT type the wifi password, but I'm going to assume that there will be cases when people type it in manually.

**Comment by bndw** [comment]
It's up, thanks @welby12 @badcat 

![image](https://user-images.githubusercontent.com/4248167/83825948-8af3f780-a68f-11ea-855a-e2a05a02c988.png)
