### ISSUE TITLE
Change behavior of "hide password" checkbox

### ISSUE THREAD

**Issue by bndw** [bndw/wifi-card#44]
Change the behavior of the Hide password checkbox as follows:
1. Hide password checkbox hides the password textarea with `display: none`. This would make is immediately invisible to the user (expected) as well as the printout.
2. Selecting "None" encryption automatically checks hide password. This will trigger (1) and hide the password textarea 
3. Changing the encryption mode from "None" to something else automatically unchecks hide password

**Comment by Mouradouchane** [comment]
Hi man , is that issue good as first one .
i think i can help if you want

**Comment by noahhefner** [comment]
So I think there's two possible approaches here: 1) Automatically check the hide password option on selection of "None" encryption type as descried in this issue or 2) hide the password entry box altogether on selection of the "None" encryption type. Option 2) seems to be a more natural implementation IMO. Thoughts?

**Comment by bndw** [comment]
@noahhefner You beat me to it! One caveat-- There is the use-case where you have a password but you might not want it on the printout. I think we need the hide password checkbox for that.

What if we changed the behavior as follows:
- Hide password checkbox hides the password textarea with `display: none`. This would make is immediately invisible to the user (expected) as well as the printout.
- Selecting "None" encryption automatically checks hide password
- Changing the encryption mode from "None" to something else automatically unchecks hide password

I _think_ that would result in the most intuitive behavior while covering all use-cases. Thoughts?

**Comment by noahhefner** [comment]
Yeah that sounds good to me! So to clarify, selecting "None" encryption would automatically check hide password **and** hide the password textarea.

Also, when selecting "None" encryption, the `network.password` field remains unchanged. In my testing, the password will actually change the QR code that is generated for None encryption. So assuming that we want to have no password for None encryption, we will need to clear `network.password` when upon selection of None encryption. Something like this:

`setNetwork({ ...network, password: '' })`

**Comment by bndw** [comment]
> So to clarify, selecting "None" encryption would automatically check hide password and hide the password textarea.

Correct

> we will need to clear network.password when upon selection of None encryption

Nice catch, that sounds like a bug. Clearing the password as you described should resolve it. (I'm not sure if it matters to the end device, but it's something worth cleaning up either way)

**Comment by bndw** [comment]
@Mouradouchane If you're familiar with React and JavaScript, this could be a reasonable first issue. Alternatively,  #46 would be a great first issue.

**Comment by Mouradouchane** [comment]
@bndw yeah i'am familiar with javascript , but i don't know anything about react 
last things , is there any installation instruction or guideline

**Comment by bndw** [comment]
@Mouradouchane Just added some in https://github.com/bndw/wifi-card/pull/47

**Comment by Mouradouchane** [comment]
i'am currently working on "show/hide" password textarea , pure javascript

**Comment by Mouradouchane** [comment]
Hi @bndw , I just want to tell you, I did my best for hours, trying to contribute to your great project, but I couldn't do anything due to my lack of knowledge of "React"
I'm sorry if I'm anoying to you, good luck
