### ISSUE TITLE
Clear network.password when "None" encryption mode is selected

### ISSUE THREAD

**Issue by bndw** [bndw/wifi-card#46]
> When selecting "None" encryption, the network.password field remains unchanged. In my testing, the password will actually change the QR code that is generated for None encryption. So assuming that we want to have no password for None encryption, we will need to clear network.password when upon selection of None encryption. Something like this:
>
> ```
> setNetwork({ ...network, password: '' })
> ```

_Originally posted by @noahhefner in https://github.com/bndw/wifi-card/issues/44#issuecomment-880759353_

**Comment by thealamu** [comment]
I would like to make a PR to close this
