### ISSUE TITLE
[Feature Request] Support multiple languages

### ISSUE THREAD

**Issue by ZJUGuoShuai** [bndw/wifi-card#49]
Maybe we can support more languages when printing the card. For example, translate the interface texts like these:

```
WiFi Login -> WiFi 登录信息
Network name -> 网络名称
Password -> 密码
Point your phone's camera at the QR Code to connect automatically -> 扫码自动连接
```

**Comment by ZJUGuoShuai** [comment]
Add a switch button or something else. If I knew how to write React I would add this feature on my own and made a PR.

**Comment by bndw** [comment]
I don't have any experience was localization in React, but a quick search turned up [this article](https://medium.com/@ricklee_10931/react-multi-lingual-with-react-i18next-57879f986168) which uses [i18next](https://www.i18next.com/).

**Comment by bndw** [comment]
@ZJUGuoShuai This has been released. You'll now find a language selector at the top of the page.

![image](https://user-images.githubusercontent.com/4248167/125968931-0a4ae551-ff22-45e1-b1b8-6fbd2aa9f941.png)
