### ISSUE TITLE
When scanned with different software, passwords can be compromised

### ISSUE THREAD

**Issue by BiYuqi** [bndw/wifi-card#57]
When I scan a QR code using a mobile app, most of the results I get are a string:
`WIFI:T:WEP;S:loadingf;P:dfdfdfdfffdfdf;;`

Only some phones's cameras that can directly scan out wifi and can connect.

Most app systems come with a native browser that can scan the QR code and connect

**Comment by bndw** [comment]
There is no compromise here. QR Codes are encoding, not encryption.

**Comment by olekstomek** [comment]
Look that you can even preview the password from the QR Code by the [application](https://play.google.com/store/apps/details?id=com.techtool.wifiqrcodepasswordscanner).
This is normal.
