### ISSUE TITLE
Alerts for passwords longer than 5 characters are not translated.

### ISSUE THREAD

**Issue by hatsu38** [bndw/wifi-card#69]
I18n.js uses `'wifi.alert.password.length.5':`, but Card.js uses `t('wifi.alert.password.5')`.

↓Example of choosing Chinese. The text of the alert is in English.

<img width="944" alt="スクリーンショット 2021-07-17 16 47 46" src="https://user-images.githubusercontent.com/16137809/126030121-345aecc1-9f26-4b8f-981a-0a7f08b85d7a.png">

**Comment by Baoyuantop** [comment]
This is my mistake 😂
