### ISSUE TITLE
Translations not working on first visit

### ISSUE THREAD

**Issue by wouterbrink** [bndw/wifi-card#75]
The translation keys are shown when first visiting the website instead of the actual translation text. 
This issue can be reproduced by visiting the website in an incognito browser window.

**Comment by bndw** [comment]
Hi @wouterbrink, I'm not sure I'm able to reproduce -- visiting the website in a Firefox incognito window renders as expected for me. Could you provide some more details? What browser are you using and what are you language settings? Could be that your browser language is something we don't yet support and the default isn't working?

![image](https://user-images.githubusercontent.com/4248167/126052902-c1b084fd-8565-46e6-a094-56b36ef774af.png)
