### ISSUE TITLE
Dockerfile can't copy "build"

### ISSUE THREAD

**Issue by rvisalm** [bndw/wifi-card#8]
Trying to build this repo from Docker, but I get an error of the type 

"COPY failed: stat /var/lib/docker/tmp/docker-builderXXXXXXX/... no such file or directory"

This seems to stem from the copy instruction "COPY build /usr/share/nginx/html" as there is no file or directory called "build" in the repository. 

Maybe I'm doing something wrong? What would you expect to happen as per this instruction?

Kind regards, and thanks for your commitment.

**Comment by bndw** [comment]
Hi @rvisalm, sorry for the lack of documentation. The `build` directory gets created by running the yarn build. Pull the latest and run:
```
make build
```

This will build and tag a `bndw/wifi-card:latest` image

**Comment by rvisalm** [comment]
Brilliant, thank you.
