### ISSUE TITLE
Suggestion: Export to SVG

### ISSUE THREAD

**Issue by thiagolopes** [bndw/wifi-card#9]
Hi, great project.

What do you think about an option to export the QR Code to an SVG file? to be able to use it in any resolution.

**Comment by bndw** [comment]
Hi @thiagolopes, thanks for the kind words.

Are you interested in an SVG of just the QR Code, or the "wifi card" including the QR Code?

**Comment by thiagolopes** [comment]
@bndw I think this could be an export option, what do you think?

**Comment by bndw** [comment]
The specific goal of this project is to quickly produce and print a "wifi card", so I think outputting a digital file is somewhat antithetical. 

However this project is OSS so you're welcome to implement an export to SVG in your own fork!

**Comment by Chocobo1** [comment]
For anyone interested. I have forked it and added an option to switch between SVG and canvas format.
Repo: https://github.com/Chocobo1/wifi-card-svg
Demo: https://chocobo1.github.io/wifi-card-svg/

**Comment by arthurfsy2** [comment]
> For anyone interested. I forked the project and added an option to switch between SVG and canvas format. Repo: https://github.com/Chocobo1/wifi-card-svg Demo: https://chocobo1.github.io/wifi-card-svg/

very nice fork! I DO love svg version, the project helped a lot.
期待svg版本已久！感谢！
