### ISSUE TITLE
Do we support Internet Explorer?

### ISSUE THREAD

**Issue by olekstomek** [bndw/wifi-card#92]
I know that hardly anyone uses this browser and Microsoft itself recommends Edge. In any case, the tool does not work in this browser (there is a white page) and an error in the console:

```
SCRIPT5009: 'Promise' is undefined
i18next.js (169,7)
```
[Undefined identifier](https://docs.microsoft.com/pl-pl/archive/scripting-docs/javascript/misc/undefined-identifier?f1url=%3FappId%3DDev12IDEF1%26l%3DPL-PL%26k%3Dk(VS.WebClient.Help.SCRIPT5009))

On July 16 there was another problem and after typing a letter in the network name field or in the password field I got a blank page with this error in the console:
![ie_wifi-card](https://user-images.githubusercontent.com/26818304/126241050-b20107f8-078b-4d81-8753-d64b7348328a.JPG)

IE Version 20H2 (OS Build 19042.1083)

**Comment by Andanan** [comment]
Just mentioning: Microsoft [announced](https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-end-of-support) a partial end of support for IE.

I surely can't make the decision whether this browser should still be supported, but in my opinion it's not worth the effort.

We could at least consider displaying a default message like "Not supported by your browser". I'm not that react-savvy, but would it be possible to just put it inside of the `<div id="root"></div>` element in the `index.html`?

**Comment by olekstomek** [comment]
I created PR https://github.com/bndw/wifi-card/pull/107 with proposal.

**Comment by bndw** [comment]
Since this is a personal project, no, we do not support Internet Explorer 😆

**Comment by olekstomek** [comment]
I think it was an expected decision. ;)

**Comment by olekstomek** [comment]
Solution https://github.com/bndw/wifi-card/pull/107 was merged so I'm closing this issue.
