### ISSUE TITLE
Hidden SSID wifi network can not be connected

### ISSUE THREAD

**Issue by jiqinga** [bndw/wifi-card#96]

**Comment by olekstomek** [comment]
It's ready to test on branch olekstomek:feature/possible-connection-to-hidden-ssid-wifi-network https://github.com/bndw/wifi-card/pull/101

**Comment by olekstomek** [comment]
Resolved: https://github.com/bndw/wifi-card/pull/101#issuecomment-883835539

**Comment by olekstomek** [comment]
Merged https://github.com/bndw/wifi-card/commit/ade8bc7d68922543ab74ee2d41920de139fd0bd3, so it can be closed.
